# Generated by Django 3.1.4 on 2020-12-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class_id', models.CharField(max_length=50, verbose_name='User Class Id')),
                ('user_class_name', models.CharField(max_length=50, verbose_name='User Class Name')),
            ],
            options={
                'verbose_name': 'UserClass',
                'verbose_name_plural': 'UserClasses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='user_id')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('user_class', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='authent.userclass', verbose_name='User Class')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
